layout : disqus
disqus :
  short_name : chrisparnin-articles
#livefyre :
#  site_id : 123
#intensedebate :
#  account : 123abc
#facebook :
#  appid : 123
#  num_posts: 5
#  width: 580
#  colorscheme: light
